# DEVELOPMENT CONFIGURATION OVERLAY
# USAGE: beet -c dev.yml config -p

pluginpath:
    - ~/Documents/Projects/Python/BeetsPluginGoingRunning/beetsplug/

format_item: "[bpm:$bpm][length:$length][genre:$genre]$artist - $album - $title"


#plugins:
#  - the
#  - inline
#  - info
#  - fromfilename
#  - duplicates
#  - convert
#  - zero
#  - bpmanalyser
#  - acousticbrainz
#  - goingrunning

goingrunning:
  song_bpm: [111, 222]
  song_len: [120, 240]
  duration: 120
  target: test
  clean_target: false
  targets:
    - name: test
        device_path: ~/Music/tmp/
        clean_target: yes
    - name: SONY
      device_path: /Volumes/WALKMAN/MUSIC/AUTO/
  trainings:
    song_bpm: [11, 22]
    halfmarathon:
      alias: "Born to run"
      song_bpm: [90, 150]
      song_len: [120, 240]
      duration: 90
    10K:
      alias: "Non mollare mai!"
      song_bpm: [155, 175]
      song_len: [120, 300]
      duration: 50
      target: SONY
    strides-1k:
      # Segments will be implemented in some future version
      segments:
        - song_bpm: [160, 180]
          song_len: [120, 240]
          duration: 5
        - song_bpm: [130, 150]
          song_len: [120, 240]
          duration: 3
      repeat_segments: 5
