# DEVELOPMENT CONFIGURATION OVERLAY
# USAGE: beet -c dev.yml config -p

pluginpath:
    - ~/Documents/Projects/Python/BeetsPluginGoingRunning/beetsplug/

format_item: "[bpm:$bpm][length:$length][genre:$genre]$artist - $album - $title"

id3v23: yes

plugins:
- the
- inline
- info
- fromfilename
- duplicates
- convert
- zero
- bpmanalyser
- acousticbrainz
- goingrunning

goingrunning:
  song_bpm: [111, 222]
  song_len: [120, 240]
  duration: 120
  target: test
  targets:
    test: /Users/jackisback/Documents/Projects/Python/BeetsPluginGoingRunning/tmp/songs/
    SONY: /Volumes/WALKMAN/MUSIC/AUTO/
  trainings:
    song_bpm: [11, 22]
    halfmarathon:
      alias: "Born to run"
      song_bpm: [90, 150]
      song_len: [120, 240]
      duration: 90


_goingrunning:
  dry-run: yes
  targets:
    test: /Users/jackisback/Documents/Projects/Python/BeetsPluginGoingRunning/tmp/songs/
    SONY: /Volumes/WALKMAN/MUSIC/AUTO/
  target: test
  clean_target: yes
  song_bpm: [90, 150]
  song_len: [120, 240]
  duration: 60

goingrunning_futute:
  dry-run: yes
  targets:
    test: /Users/jackisback/Documents/Projects/Python/BeetsPluginGoingRunning/tmp/songs/
    SONY: /Volumes/WALKMAN/MUSIC/AUTO/
  default_target: test
  clean_target: yes
  song_bpm: [90, 150]
  song_len: [120, 240]
  duration: 60
  trainings:
    halfmarathon:
      song_bpm: [90, 150]
      song_len: [120, 240]
      duration: 120
    strides-1k:
      # Segments will be implemented in some future version
      segments:
        -
          song_bpm: [160, 180]
          song_len: [120, 240]
          duration: 5
        -
          song_bpm: [130, 150]
          song_len: [120, 240]
          duration: 3
      repeat_segments: 5


