# DEVELOPMENT CONFIGURATION FILE
# USAGE: export environment variable BEETSDIR=/path/to/BEETSDIR
# then: `beets config -p` should list this file

#directory: Music
#library: library.db
directory: /Volumes/J/Music/
library: ~/.config/beets/real_library.db
asciify_paths: yes
id3v23: yes

pluginpath:
    - ~/Documents/Projects/Python/BeetsPluginGoingRunning/beetsplug/

plugins:
    - info
    - goingrunning

#format_item: "[format:$format][bpm:$bpm] ::: $path"
format_item: "[MA:$mood_aggressive][bpm:$bpm][gender:$gender][year:$year] $artist ::: $title"

import:
    copy: yes
    autotag: no

goingrunning:
  # todo: this (clean_target) is dangerous here and should be checked ONLY on the target
  clean_target: no
  targets:
    test:
      device_root: ~/Documents/Projects/Python/BeetsPluginGoingRunning/BEETSDIR/Target1
      device_path: MUSIC/AUTO
      clean_target: yes
      delete_from_device:
        - xyz.txt
    SONY:
      device_root: /Volumes/WALKMAN
      device_path: MUSIC/AUTO
      clean_target: yes
      delete_from_device:
        - STDBDATA.DAT
        - STDBSTR.DAT
  trainings:
    fallback:
      alias: FALLBACK
      query:
        bpm: 90..140
      duration: 60
      target: test
    test:
      query:
        artist: "ZZ TOP"
        mood_aggressive: 0.4..09
      duration: 30
    halfmarathon:
      alias: HM
      query:
        bpm: 90..150
        length: 120..300
        mood_aggressive: 0.3..0.7
      ordering:
        year: 100
        #bpm: 50
        #mood_aggressive: 50
      duration: 60
      #target: SONY
